run:
  skip-dirs:
    - vendor

linters:
  enable-all: true
  disable:
  - forbidigo
  - wsl
  - varnamelen
  - gofumpt
  - tagliatelle
  - exhaustivestruct
  - exhaustruct
  - nlreturn
  - gci
  - funlen
  - nestif
  - cyclop
  - nosnakecase
  - gomnd
  - gochecknoglobals
  - gosec