FROM ubuntu:latest

RUN apt update && apt install openssh-server sudo -y

RUN echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN    echo "root:password" | chpasswd

RUN service ssh start

EXPOSE 22

CMD ["/usr/sbin/sshd","-D"]